name = "ydb-ai-dev-kit"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = false

[vars]
GITHUB_REPO = "ydb-platform/ai-dev-kit"

[[routes]]
pattern = "ai.ydb.sh"
custom_domain = true
